import { Inter, } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { getDictionary } from "./dictionaries";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Apartments And Villas For Rent And Sale In Maadi Real Estate | Cairo | Egypt",
  description: "Generated by create next app",
  openGraph: {
    title: "Apartments And Villas For Rent And Sale In Maadi Real Estate | Cairo | Egypt"
  }
};

export default async function RootLayout({ children, params }) {
  const translate = await getDictionary(params.lang)
  return (
    <html lang={params.lang}>
      <body dir={params.lang === "ar" ? 'rtl' : 'ltr'} className={`${inter.className} `}>

        <Navbar translate={translate} lang={params.lang} />
        {children}
        {/* <Footer translate={translate} lang={params.lang}/> */}
      </body>
    </html>
  );
}
